# SimplishRevision.cmake — write the engine's source revision into a header
#
# Run as a script (cmake -P) on every build by the simplish-revision target
# in src/editor/deploy/. The header is rewritten only when the revision
# changes, so an unchanged tree rebuilds nothing.
#
#   -DSOURCE_DIR=<the engine checkout>  -DOUT=<the header to write>
#
# The revision is `git describe --always --dirty`: the same commit on every
# platform, and marked when the tree has uncommitted changes. Without git,
# "unknown".

execute_process(
    COMMAND git describe --always --dirty --abbrev=40
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE _revision
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _result)
if(NOT _result EQUAL 0 OR _revision STREQUAL "")
    set(_revision "unknown")
endif()

set(_header "#pragma once

/// @file simplish-revision.h
/// @brief The engine revision this binary was built from. Generated by
/// cmake/SimplishRevision.cmake on every build; do not edit.
/// @par Threading
/// Constants.

#include <string_view>

namespace eng::editor {

/// `git describe --always --dirty` of the engine checkout, or \"unknown\".
inline constexpr std::string_view SIMPLISH_REVISION = \"${_revision}\";

}  // namespace eng::editor
")

if(EXISTS "${OUT}")
    file(READ "${OUT}" _existing)
endif()
if(NOT _existing STREQUAL _header)
    file(WRITE "${OUT}" "${_header}")
endif()
